name: "Upload data to S3 bucket"
description: "Upload data"
inputs:
    account_id:
      description: "account id"
      required: true
    bucket_name:
      description: "S3 bucket host"
      required: true
runs:
  using: composite
  steps:
    - name: Upload json data file
      shell: bash
      run: |
        aws --version
        aws s3 ls

        echo "account id: ${{inputs.account_id}}"
        echo "S3 bucket: ${{inputs.bucket_name}}"
        