name: "Upload data to S3 bucket"
description: "Upload data"
inputs:
    account_id:
      description: "account id"
      required: true
    bucket_name:
      description: "S3 bucket host"
      required: true
runs:
  using: composite
  steps:
    - name: Upload json data file
      shell: bash
      run: |
        echo "Update aws cli: "
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -qq awscliv2.zip
        sudo ./aws/install
        aws --version
        
        echo "account id: ${{inputs.account_id}}"
        echo "S3 bucket: ${{inputs.bucket_name}}"
        