name: "Upload data to S3 bucket"
description: "Upload data"
inputs:
    bucket_name:
      description: "S3 bucket host"
      required: true
runs:
  using: composite
  steps:
    - name: Upload json data file
      shell: bash
      run: |
        aws --version
        cd src/main/resources/data
        ls
        echo "Uploading to S3 bucket: ${{inputs.bucket_name}}"
        aws s3 sync . ${{inputs.bucket_name}}