name: Upload data for vocabulary management
run-name: ${{ github.actor }} Vocabulary leaning application deployment 🚀
on:
  workflow_dispatch:
    inputs:
      upload_data:
        description: Upload vocabulary data?
        type: boolean
        required: true
        default: true
      deploy_ui:
        description: Deploy UI component?
        type: boolean
        required: true
        default: true
    push:
      branches:
        - main

jobs:
  Upload-Data-To-S3:
    runs-on: ubuntu-latest
    if: inputs.upload_data || inputs.deploy_ui
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        if: inputs.upload_data
        uses: actions/checkout@v4

      - name: Configure Credentials
        if: inputs.upload_data
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::998649062847:role/github_workflow_for_s3
          aws-region: us-east-1

      - name: Deploy to S3
        uses: ./.github/actions/upload_data
        with:
          bucket_name: "s3://e-tips-static-site/assests/data"

  Deploy-UI-To-S3:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      if: inputs.deploy_ui
      needs: [Upload-Data-To-S3]
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Configure Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::998649062847:role/github_workflow_for_s3
            aws-region: us-east-1

        - name: Deploy to S3
          uses: ./.github/actions/deploy_ui
          with:
            bucket_name: "s3://e-tips-static-site"