name: Upload data for vocabulary management
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  Checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::998649062847:role/github_workflow_for_s3
          aws-region: us-east-1

  Upload-Data-To-S3:
    runs-on: ubuntu-latest
    needs: [Checks]
    steps:
      - name: Deploy to S3
        uses: ./.github/actions/upload_data
        with:
          bucket_name: "s3://e-tips-static-site/assests/data"

  Deploy-UI-To-S3:
      runs-on: ubuntu-latest
      needs: [Upload-Data-To-S3]
      steps:
        - name: Deploy to S3
          uses: ./.github/actions/deploy_ui
          with:
            bucket_name: "s3://e-tips-static-site"